Portfolio desktop version
LethaboMot/building-portfolio pull request #5
Opened 2023-01-19 08:00 UTC by LethaboMot

in project I:

Added media query
Made the content in the cards side by side
Made the about me side by side with the `language`, `framework`, and `skills`

2023-01-19 10:44 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @LethaboMot    👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far 👍 
 there are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔ No Linter errors
✔ Professional Readme
✔ Professional PR

## Required Changes ♻️

- Check the comments below 👇

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 10:44 UTC, TuyishimireEric commented on style.css
> +  }
- [ ] **Good job on switching places with each project 🥇** However, it would be better to adjust the space on both ```margin-left``` and ```margin-right``` to replicate the Figma template 👍 
- [ ] It would be better also to remove the border color for the project card as they change color only on the ```hover``` state 👍 👍 
- [ ] for the row below the heading, good job on adding separator 👍, However it would be better to fix the alignment and the spacing to replicate the Figma design 

- [ ] below 👇 , I have highlighted some issues to be fixed for your reference 
![image](https://user-images.githubusercontent.com/102757126/213417850-6c948d04-9918-428f-bd6b-db60758c52d9.png)

2023-01-19 10:44 UTC, TuyishimireEric commented on style.css
> +  }
- [ ] I think for the about section, it would be better to adjust the [margin and padding ](https://www.geeksforgeeks.org/css-margins-padding/) to replicate the Figma design as much as possible 

- [ ] Kindly the on the Figma design, There are 2 blocks The left one takes 40%, and the right one the remaining 60% of the page's width, and the contents of each are aligned to the right. on your design, the two parts seem to be identical, so it would be better to fix this issue too 😎😎

![image](https://user-images.githubusercontent.com/102757126/213421898-e80ab220-7c3e-49a5-a155-092a5b9a4d00.png)

2023-01-20 12:55 UTC, osamaashraf6 requested changes
Hi  @LethaboMot ☺️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights ✔️

- [x] Descriptive READme file in a professional way.
- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 12:55 UTC, osamaashraf6 commented on index.html
> +        </h1>
- [ ] Good job 😃 at implementing the required changes, but as stated by the previous reviewer ,kindly😊 try tofix the position and the size of the background image to be like the Figma Design, so with that your design will be attractive to the visitors👌

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/213696512-3226bc13-7a97-4d9c-8e55-43afefa2e4d5.png)   |   ![image](https://user-images.githubusercontent.com/83360636/213696442-e12325b4-f746-46de-93d0-8053ea47b32a.png)   |

2023-01-20 12:55 UTC, osamaashraf6 commented on index.html
> -        <p class="center">LET'S CONNECT</p>
- [ ] kindly 😊as stated by the previous reviewer try to fix the margin between elements here to be like the Figma Design 💯

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/213697281-b612ca7f-7cdb-4c02-916c-5f18766e27f4.png)|    ![image](https://user-images.githubusercontent.com/83360636/213697126-69ee1370-714f-4ca2-9bcd-1ff57d562591.png)|

2023-01-20 12:55 UTC, osamaashraf6 commented on index.html
> +            <ul class="Socials">
- [ ] You did well😃, but as stated by the previous reviewer please 😊try to fix the padding and margin in this section it will be better if you put a container class and wrap all elements to give them the correct margin and padding to be like the Figma Design 👌

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/213698650-c1124bd5-c91e-4eb8-9eb9-a2b0735fa89f.png)|   ![image](https://user-images.githubusercontent.com/83360636/213698592-d0ee0750-b2f9-467e-8e06-0493866399d3.png) |

2023-01-20 19:34 UTC, BregornOriginal requested changes
## Hi @LethaboMot  

## Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![one-step-closer-one-more](https://user-images.githubusercontent.com/93630700/213790183-fbdb59d2-b408-41b2-ae15-32bee0f5f9af.gif)

 ## Highlights

✅ Linters are passing
✅ Good design 💯 
✅ Good commit history

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 19:34 UTC, BregornOriginal commented on style.css
> +
- [ ] Kindly check your desktop version styling, since in your layout there's some elements overlaping

![image](https://user-images.githubusercontent.com/93630700/213789820-daab6ce4-cab6-4ba3-ab8f-fb32af5854c5.png)

2023-01-20 21:06 UTC, jerryowusu requested changes
Hi @LethaboMot  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![this close2](https://user-images.githubusercontent.com/65233860/213805086-2c6a4ba0-a6e2-4c24-b286-19db7c13eedf.gif)

 ## Highlights
All linters are passing :heavy_check_mark: 
Great effort so far :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 21:06 UTC, jerryowusu commented on style.css
> +
Well done for solving the overlapping issue,however, adding a margin of 400px to the left side has created another problem by shifting the whole section to the right side, hence some parts are hidden as shown in the image below. :point_down: Kindly ensure that your design matches that of the figma design in terms of margins, paddings or layouts as stipulated in the figma design. :pray: 

Your design.

![Screenshot from 2023-01-20 20-55-34](https://user-images.githubusercontent.com/65233860/213804631-511744a6-23cb-4c5c-b487-b191b6943528.png)


Figma design 

![Screenshot from 2023-01-20 20-57-53](https://user-images.githubusercontent.com/65233860/213804657-a1309954-1c78-4731-83a2-0592ce687b2b.png)

2023-01-20 21:06 UTC, jerryowusu commented on style.css
> +  /* font-size: 4.3vw; */
[OPTIONAL] Please do not leave unused code in your code base as comments since it makes it bulky and slows down performance. Kindly consider removing all commented codes. :wink:

2023-01-20 23:01 UTC, iambenkis approved these changes
Hi @LethaboMot , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@iambenkis** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 23:01 UTC, iambenkis commented on index.html
> +            </p>
- [ ] [**OPTIONAL**] @LethaboMot I happy for these project you're bringing to the end :clap: , however you should sure this position stick to the Figma design by centering this section :cactus: 
![Screenshot from 2023-01-21 00-52-07](https://user-images.githubusercontent.com/80458199/213820314-fcdbe449-b1d2-4a2e-8c1d-b53a8acc1ac5.png)

2023-01-23 08:23 UTC, merged