Portfolio details popup window
LethaboMot/building-portfolio pull request #9
Opened 2023-01-31 12:54 UTC by LethaboMot

in the project we:

Added the modal.js file which contains the element for the popup
Added CSS to style the desktop and  mobile versions of the popup

2023-01-31 16:30 UTC, LethaboMot commented on index.html
>                  <h2 class="heading">Tonic</h2>
I thought the popup cards should be created dynamically.

2023-01-31 21:04 UTC, NahnahAJ requested changes
Hi @LethaboMot and @enis-memic , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media4.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

 ## Highlights
- Linters rightly set up and passing :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Good commit messages :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 21:04 UTC, NahnahAJ commented on style.css
>      display: grid;
- [ ] Please ensure that you follow the Figma Popup design as much as possible. From the screenshot below, you can see that your design has a few spacing issues, and aside from that, the font color used for the `BACK END DEV` and `2015` are different from the Figma design. Kindly fix  this as well :wink: 
- [ ] KIndly do same for the desktop Popup as well :100: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/215881622-0e842b98-2e1d-4b07-a130-66c8ce6dc286.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/215881847-dcecf6b1-cac4-44d6-8d08-58187e7e36a9.png)

2023-02-01 17:37 UTC, NahnahAJ approved these changes
Hi @LethaboMot and @enis-memic , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>

## Highlights
- No linter errors :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- Professional README :100: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 18:42 UTC, merged